# Generated by Django 5.2.9 on 2026-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=100)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(choices=[('', 'Select Bus Type'), ('AC', 'AC'), ('NON-AC', 'NON-AC'), ('SLEEPER', 'Sleeper')], max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
